web:
  port: 80

endpoints:
  - name: Public Website
    url: "https://devopsfinalcontainer-ajfyhjachbgchwgu.canadacentral-01.azurewebsites.net/"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 10000"
