endpoints:
  - name: Local nginx
    url: "nginx_server:80"
    interval: 60s
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 500"   # Response time must be under 500ms
  - name: External Website
    url: "devopsfinalcontainer-ajfyhjachbgchwgu.canadacentral-01.azurewebsites.net"
    interval: 60s
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 1000"  # Response time must be under 500ms
  - name: External Status 
    url: "devopsfinalcontainer-ajfyhjachbgchwgu.canadacentral-01.azurewebsites.net/status"
    interval: 60s
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 500"   # Response time must be under 500ms
