services:
  nginx:
    build:
      context: .
      dockerfile: ./dockers/Dockerfile.nginx
    image: c0954832/nginx-server:latest
    container_name: nginx_server
    volumes:
      - /home/Barrack1393/ssl/cloudflare_scrumstormers.pem:/etc/ssl/certs/cloudflare_scrumstormers.pem:ro
      - /home/Barrack1393/ssl/cloudflare_scrumstormers.key:/etc/ssl/private/cloudflare_scrumstormers.key:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - uptime-kuma
    restart: unless-stopped

  uptime-kuma:
    build:
      context: .
      dockerfile: ./dockers/Dockerfile.uptime-kuma
    image: c0954832/uptime-kuma-custom:latest
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    restart: unless-stopped

  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    environment:
      - API_KEY=${CF_API_KEY}
      - ZONE=${CF_ZONE}
      - PROXIED=true
    restart: unless-stopped

