version: "3.8"

services:
  nginx:
    build: .
    container_name: nginx_server
    ports:
      - "8080:80"
    depends_on:
      - uptime-kuma
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ./settings_files/kuma/kumadata:/app/data
      - ./settings_files/kuma/init:/init
    ports:
      - "3001:3001"
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/init/init.sh"]
  
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    environment:
      - API_KEY=${CF_API_KEY}
      - ZONE=${CF_ZONE}
      - SUBDOMAIN=${CF_SUBDOMAIN}
      - PROXIED=true
    restart: unless-stopped
