services:
  nginx:
    build:
      context: .
      dockerfile: ./dockers/Dockerfile.nginx
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      - uptime-kuma
    restart: unless-stopped

  uptime-kuma:
    build:
      context: .
      dockerfile: ./dockers/Dockerfile.uptime-kuma
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    restart: unless-stopped